#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
source "$ROOT_DIR/scripts/common.sh"

: "${APP_NAME:=ecomm}"
: "${DEPLOY_ROOT:=/opt/ecomm}"
: "${BACKEND_DIR:=$DEPLOY_ROOT/backend}"
: "${SERVICE_NAME:=ecomm-backend}"
: "${JAVA_VERSION:=17}"
: "${PORT:=8080}"

: "${DB_URL:=jdbc:postgresql://127.0.0.1:5432/ecomm}"
: "${DB_USERNAME:=ecomm}"
: "${DB_PASSWORD:=ecomm}"

: "${JWT_ISSUER:=ecomm}"
: "${JWT_SECRET:=change-this-secret-to-a-long-random-string}"
: "${CORS_ALLOWED_ORIGINS:=http://localhost:4000}"

: "${BACKEND_JAR_NAME:=ecomm-backend.jar}"
: "${BACKEND_MAIN_JAR:=$DEPLOY_ROOT/$BACKEND_JAR_NAME}"
: "${SKIP_TESTS:=true}"

require_root

log "Building backend (Spring Boot) and deploying as a standalone Java service-less jar (systemd not configured by request)."

build_backend() {
  local repo_backend_dir="$ROOT_DIR/backend"
  if [[ ! -d "$repo_backend_dir" ]]; then
    err "backend directory not found at $repo_backend_dir"
    exit 1
  fi

  if ! have_cmd mvn; then
    # Maven is commonly available via dnf/yum; try best-effort install
    if is_redhat_like && have_cmd dnf; then
      log "Installing Maven (best-effort)..."
      dnf -y install maven || true
    elif is_redhat_like && have_cmd yum; then
      log "Installing Maven (best-effort)..."
      yum -y install maven || true
    fi
  fi

  if ! have_cmd mvn; then
    err "mvn not found. Install Maven before running this script."
    exit 1
  fi

  log "Maven build: mvn clean package"
  if [[ "$SKIP_TESTS" == "true" ]]; then
    (cd "$repo_backend_dir" && mvn -q clean package -DskipTests)
  else
    (cd "$repo_backend_dir" && mvn -q clean package)
  fi

  # Find jar
  local jar
  jar="$(ls -1 "$repo_backend_dir"/target/*.jar | head -n 1 || true)"
  if [[ -z "$jar" ]]; then
    err "Backend jar not found under backend/target/*.jar"
    exit 1
  fi

  log "Copying jar to deployment dir: $BACKEND_MAIN_JAR"
  ensure_dir "$DEPLOY_ROOT"
  cp -f "$jar" "$BACKEND_MAIN_JAR"
}

write_env_file() {
  ensure_dir "$BACKEND_DIR"
  local env_file="$BACKEND_DIR/${SERVICE_NAME}.env"

  cat > "$env_file" <<EOF
# Generated by deploy script
APP_PORT=${PORT}

SPRING_DATASOURCE_URL=${DB_URL}
SPRING_DATASOURCE_USERNAME=${DB_USERNAME}
SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}

APP_CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS}
APP_JWT_ISSUER=${JWT_ISSUER}
APP_JWT_SECRET=${JWT_SECRET}
EOF

  chmod 600 "$env_file"
  log "Wrote env file: $env_file"
}

run_instructions() {
  cat <<EOF

Backend deployed.

To start it manually (systemd was not requested):

  export $(grep -v '^#' $BACKEND_DIR/${SERVICE_NAME}.env | xargs -d '\n' -I{} echo {})
  # OR simply load the env file:
  set -a
  source $BACKEND_DIR/${SERVICE_NAME}.env
  set +a

  nohup java \
    -Dserver.port=${PORT} \
    -Dspring.datasource.url=${DB_URL} \
    -Dspring.datasource.username=${DB_USERNAME} \
    -Dspring.datasource.password=${DB_PASSWORD} \
    -Dapp.cors.allowed-origins=${CORS_ALLOWED_ORIGINS} \
    -Dapp.jwt.issuer=${JWT_ISSUER} \
    -Dapp.jwt.secret=${JWT_SECRET} \
    -jar ${BACKEND_MAIN_JAR} \
    > ${BACKEND_DIR}/backend.log 2>&1 &

Logs:
  tail -f ${BACKEND_DIR}/backend.log
EOF
}

main() {
  build_backend
  write_env_file
  run_instructions
}

main "$@"

